### ISSUE TITLE
拷贝本机三码到 OC 配置时，SystemUUID 格式问题

### ISSUE THREAD

**Issue by jayqizone** [haoke123/MacSerialTransporter#1]
复制本机三码到 OC 配置时，SystemUUID 也同时复制了，但是是连起来的字符串，用此配置启动会报错，改为 - 字符分隔的格式后启动正常。可能是个问题，麻烦确认下

**Comment by haoke123** [comment]
已经修复 多谢

> 复制本机三码到 OC 配置时，SystemUUID 也同时复制了，但是是连起来的字符串，用此配置启动会报错，改为 - 字符分隔的格式后启动正常。可能是个问题，麻烦确认下

**Comment by jayqizone** [comment]
谢谢👍
